### PR TITLE
feat: update dependencies and rust edition

### PR DESCRIPTION
**Pull request by somehowchris**
I don't wanna regulate how you manage dependencies but here are my two cents.

Developers should know which crate and under which version things run, not only for historic reasons but also for maintenance and security reasons. There is a reason why many use semantic versioning.

Also, if people feel like overwriting versions of crates, they can do it with cargo, so its and opt-in not an opt-out.

So here's my proposal
 - declare crates down to `x.y.z`
 - active renovate or dependabot, so you or other maintainers know when things are moving (personally prefering renovate, not contained in this pr)
 - move to rust 2021
 - explicitly forbid unsafe code (you already included that)
 - set a `rust-version` within the Cargo.toml to manifest a msrv (not contained in this pr)

### CODE REVIEW

**Comment by allan2** [comment]
Good suggestions. It may be better if you open separate issues. I would love if someone fixed the CI. You make good points about versioning.

I'd prefer to stay on 2018 at this time because it will build on more systems. I don't see a compelling reason to move to 2021 yet.

**Comment by somehowchris** [comment]
Do you have a list of systems you would like to support as build targets?

**Comment by allan2** [comment]
@somehowchris Feel free to suggest supporting more build targets!

**Comment by paolobarbolini** [comment]
Drive-by review: this PR is completely useless. `cargo update` can already update dependencies to their latest allowed semver range. Doing so in Cargo.toml just breaks the ability to use older versions of dependencies. This should usually only be done when dependencies from `cargo update -Z minimal-versions` are so old they are unsound or don't work with the project because of missing APIs, bugs etc.

**Comment by sonro** [comment]
Closing this PR as the desirable changes have already been implemented.

**Pull request closed without merging**
